//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soruSor.servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class cevap
    {
        public cevap()
        {
            this.favori = new HashSet<favori>();
        }
    
        public int cevapId { get; set; }
        public int soruId { get; set; }
        public string cevap1 { get; set; }
        public System.DateTime cevapTarih { get; set; }
    
        public virtual Soru Soru { get; set; }
        public virtual ICollection<favori> favori { get; set; }
    }
}
