//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soruSor.servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public kullanici()
        {
            this.favori = new HashSet<favori>();
            this.Soru = new HashSet<Soru>();
        }
    
        public int kullaniciId { get; set; }
        public string kullaniciAd { get; set; }
        public string kullaniciSifre { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
    
        public virtual ICollection<favori> favori { get; set; }
        public virtual ICollection<Soru> Soru { get; set; }
    }
}
